apiVersion: v1
kind: Namespace
metadata:
  name: it-tools
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: it-tools
  namespace: it-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: it-tools
  template:
    metadata:
      labels:
        app: it-tools
    spec:
      containers:
        - name: it-tools
          image: corentinth/it-tools:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: it-tools-svc
  namespace: it-tools
spec:
  selector:
    app: it-tools
  ports:
    - port: 80
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: it-tools-cert
  namespace: it-tools
spec:
  secretName: it-tools-cert-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "tools.local.lamers.tech"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: it-tools
  namespace: it-tools
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`tools.local.lamers.tech`)
      kind: Rule
      services:
        - name: it-tools-svc
          port: 80
  tls:
    secretName: it-tools-cert-tls